name: CI

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
      - 'bugfix/*'

permissions:
  contents: read
  actions: read

jobs:
  ci:
    name: CI
    uses: CCPL-Solutions/ccpl-devops/.github/workflows/ci_workflow.yml@master
    secrets:
      USERNAME: ${{ secrets.USERNAME }}
      USERNAME_ACCESS_TOKEN: ${{ secrets.USERNAME_ACCESS_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
