name: PR to Develop

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: read
  actions: read

jobs:
  pr-check:
    name: PR Check
    uses: CCPL-Solutions/ccpl-devops/.github/workflows/libs/feature_hotfix_push_workflow.yml@master
    secrets:
      USERNAME: ${{ secrets.USERNAME }}
      USERNAME_ACCESS_TOKEN: ${{ secrets.USERNAME_ACCESS_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
