name: Publish Snapshot from Develop

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  actions: read
  packages: write
      
jobs:
  publish-snapshot:
    name: Publish Snapshot
    uses: CCPL-Solutions/ccpl-devops/.github/workflows/publish_snapshot_workflow.yml@master
    secrets:
      USERNAME: ${{ secrets.USERNAME }}
      USERNAME_ACCESS_TOKEN: ${{ secrets.USERNAME_ACCESS_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
