name: Publish Release

on:
  push:
    branches:
      - 'release/*'

permissions:
  contents: read
  actions: read
  packages: write
      
jobs:
  publish-snapshot:
    name: Publish Snapshot
    uses: CCPL-Solutions/ccpl-devops/.github/workflows/publish_release_workflow.yml@master
    secrets:
      USERNAME: ${{ secrets.USERNAME }}
      USERNAME_ACCESS_TOKEN: ${{ secrets.USERNAME_ACCESS_TOKEN_PIBLISH }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
