name: Publish Artifact

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
  push:
    branches:
      - release/*

permissions:
  contents: write
  actions: read
  packages: write
      
jobs:
  publish-artifact:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true && (startsWith(github.head_ref, 'feature/') || startsWith(github.head_ref, 'bugfix/') || startsWith(github.head_ref, 'hotfix/')))
    name: Publish Artifact
    uses: CCPL-Solutions/ccpl-devops/.github/workflows/publish_artifact_workflow.yml@master
    secrets:
      USERNAME: ${{ secrets.USERNAME }}
      USERNAME_ACCESS_TOKEN: ${{ secrets.USERNAME_ACCESS_TOKEN_PIBLISH }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
