name: Push Event Pipe

on:
  push:
    branches:
      - 'feature/*'

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  call-shared-workflow:
    uses: CCPL-Solutions/ccpl-devops/.github/workflows/push_event_workflow.yml@master
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      TOKEN_EXAMPLE: ${{ secrets.TOKEN_EXAMPLE }}
