name: Push Event Pipe

on:
  push:
    branches:
      - 'feature/*'

permissions:
  contents: read
  actions: read
  packages: read

jobs:
  push-event-pipi:
    name: PushEvenPipe
    uses: CCPL-Solutions/ccpl-devops/.github/workflows/push_event_workflow.yml@master
    secrets:
      USERNAME: ${{ secrets.USERNAME }}
      USERNAME_ACCESS_TOKEN: ${{ secrets.USERNAME_ACCESS_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
